"""
Bitcoin constants and values
"""

# Bitcoin Script Opcodes
OP_0 = 0x00
OP_1 = 0x51
OP_PUSHBYTES_20 = 0x14
OP_PUSHBYTES_32 = 0x20
OP_DUP = 0x76
OP_EQUAL = 0x87
OP_EQUALVERIFY = 0x88
OP_HASH160 = 0xa9
OP_CHECKSIG = 0xac

# Global Key Types Dictionary (BIP-174)
PSBT_GLOBAL_TYPES = {
    0: "PSBT_GLOBAL_UNSIGNED_TX",
    1: "PSBT_GLOBAL_XPUB",
    2: "PSBT_GLOBAL_TX_VERSION",
    3: "PSBT_GLOBAL_FALLBACK_LOCKTIME",
    4: "PSBT_GLOBAL_INPUT_COUNT",
    5: "PSBT_GLOBAL_OUTPUT_COUNT",
    6: "PSBT_GLOBAL_TX_MODIFIABLE",
    7: "PSBT_GLOBAL_SP_ECDH_SHARE",
    8: "PSBT_GLOBAL_SP_DLEQ_PROOF",
    251: "PSBT_GLOBAL_VERSION",
    252: "PSBT_GLOBAL_PROPRIETARY"
}

# Per-Input Key Types Dictionary (BIP-174)
PSBT_IN_TYPES = {
    0: "PSBT_IN_NON_WITNESS_UTXO",
    1: "PSBT_IN_WITNESS_UTXO",
    2: "PSBT_IN_PARTIAL_SIG",
    3: "PSBT_IN_SIGHASH_TYPE",
    4: "PSBT_IN_REDEEM_SCRIPT",
    5: "PSBT_IN_WITNESS_SCRIPT",
    6: "PSBT_IN_BIP32_DERIVATION",
    7: "PSBT_IN_FINAL_SCRIPTSIG",
    8: "PSBT_IN_FINAL_SCRIPTWITNESS",
    9: "PSBT_IN_POR_COMMITMENT",
    10: "PSBT_IN_RIPEMD160",
    11: "PSBT_IN_SHA256",
    12: "PSBT_IN_HASH160",
    13: "PSBT_IN_HASH256",
    14: "PSBT_IN_PREVIOUS_TXID",
    15: "PSBT_IN_OUTPUT_INDEX",
    16: "PSBT_IN_SEQUENCE",
    17: "PSBT_IN_REQUIRED_TIME_LOCKTIME",
    18: "PSBT_IN_REQUIRED_HEIGHT_LOCKTIME",
    19: "PSBT_IN_TAP_KEY_SIG",
    20: "PSBT_IN_TAP_SCRIPT_SIG",
    21: "PSBT_IN_TAP_LEAF_SCRIPT",
    22: "PSBT_IN_TAP_BIP32_DERIVATION",
    23: "PSBT_IN_TAP_INTERNAL_KEY",
    24: "PSBT_IN_TAP_MERKLE_ROOT",
    26: "PSBT_IN_MUSIG2_PUB_NONCE",
    27: "PSBT_IN_MUSIG2_PARTICIPANT_PUBKEYS",
    28: "PSBT_IN_MUSIG2_PARTIAL_SIG",
    29: "PSBT_IN_SP_ECDH_SHARE",
    30: "PSBT_IN_SP_DLEQ_PROOF",
    252: "PSBT_IN_PROPRIETARY"
}

# Per-Output Key Types Dictionary (BIP-174)
PSBT_OUT_TYPES = {
    0: "PSBT_OUT_REDEEM_SCRIPT",
    1: "PSBT_OUT_WITNESS_SCRIPT",
    2: "PSBT_OUT_BIP32_DERIVATION",
    3: "PSBT_OUT_AMOUNT",
    4: "PSBT_OUT_SCRIPT",
    5: "PSBT_OUT_TAP_INTERNAL_KEY",
    6: "PSBT_OUT_TAP_TREE",
    7: "PSBT_OUT_TAP_BIP32_DERIVATION",
    252: "PSBT_OUT_PROPRIETARY"
}

# Automatically create constants from dictionaries
globals().update({name: value for value, name in PSBT_GLOBAL_TYPES.items()})
globals().update({name: value for value, name in PSBT_IN_TYPES.items()})
globals().update({name: value for value, name in PSBT_OUT_TYPES.items()})

# Export all constants
__all__ = [
    # Script opcodes
    'OP_0',
    'OP_1',
    'OP_PUSHBYTES_20',
    'OP_PUSHBYTES_32',
    'OP_DUP',
    'OP_EQUAL',
    'OP_EQUALVERIFY',
    'OP_HASH160',
    'OP_CHECKSIG',
    # PSBT type dictionaries
    'PSBT_GLOBAL_TYPES',
    'PSBT_IN_TYPES',
    'PSBT_OUT_TYPES',
] + list(PSBT_GLOBAL_TYPES.values()) + list(PSBT_IN_TYPES.values()) + list(PSBT_OUT_TYPES.values())
